site_name: "Отчёты по веб-разработке"
site_description: "Сборник отчётов по лабораторным работам Гордеева Артёма"
site_author: "Гордеев Артём, K3339"

theme:
  name: mkdocs
  language: ru
  palette:
    - scheme: default
      primary: indigo
      accent: indigo

nav:
  - Лабораторная работа 1: index.md
  - Лабораторная работа 2: lab2.md
